# Generated by Django 3.0 on 2019-12-03 17:56

import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('icon', models.URLField(blank=True)),
                ('api_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('last_update', models.DateField(auto_now=True)),
            ],
        ),
    ]
