version: '3'

services:
  db:
    image: "mdillon/postgis:11-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "limehome"
      POSTGRES_USER: "limehome"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: